#!/bin/sh

datum=`date "+%Y-%m-%d_%H-%M"`

mkdir /home/pi/si-backup/$datum
echo Backing up ../si-backup/$datum

cp -r *				/home/pi/si-backup/$datum
cp -r /var/www/html/*		/home/pi/si-backup/$datum
cp -r /var/www/cgi-bin/*	/home/pi/si-backup/$datum

WC=`find . -name '*.py' | xargs wc -l | tail -1`
echo Python lines $WC
